logging.level.org.springframework.boot.autoconfigure=DEBUG
H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Emir
spring.datasource.password=Emir
spring.h2.console.enabled=true
spring.jpa.show-sql=true
server.address=127.0.0.1
server.port=8080